//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceWebRole1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public System.DateTime TimeAdded { get; set; }
        public int User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
